export const MenuJson = [
  {
    name: '产品体系',
    path: '/',
    active: false,
    icon: '',
    level: 'menu-level1',
    children: [
      {
        name: '大数据平台',
        path: '/',
        active: false,
        icon: 'big-data',
        level: 'menu-level2',
        children: [
          {
            name: '数据采集/管理平台',
            path: '/',
            active: false,
            icon: '',
            level: 'menu-level3',
            children: [
              {
                name: '自主采集汇总平台',
                path: '/',
                active: false,
                icon: '',
                level: 'menu-level4',
              },
              {
                name: '数据工厂系统',
                path: '/',
                active: false,
                icon: '',
                level: 'menu-level4',
              },
              {
                name: '指标建模系统',
                path: '/',
                active: false,
                icon: '',
                level: 'menu-level4',
              },
            ],
          },
          {
            name: '数据治理平台',
            path: '/',
            active: false,
            icon: '',
            level: 'menu-level3',
            children: [
              {
                name: '元数据管理平台',
                path: '/',
                active: false,
                icon: '',
                level: 'menu-level4',
              },
              {
                name: '主数据管理平台',
                path: '/',
                active: false,
                icon: '',
                level: 'menu-level4',
              },
              {
                name: '数据质量管理平台',
                path: '/',
                active: false,
                icon: '',
                level: 'menu-level4',
              },
              {
                name: '数据标准管理平台',
                path: '/',
                active: false,
                icon: '',
                level: 'menu-level4',
              },
              {
                name: '数据质量管理平台',
                path: '/',
                active: false,
                icon: '',
                level: 'menu-level4',
              },
              {
                name: '数据资产管理平台',
                path: '/',
                active: false,
                icon: '',
                level: 'menu-level4',
              },
            ],
          },
          {
            name: '数据储存平台',
            path: '/',
            active: false,
            icon: '',
            level: 'menu-level3',
            children: [
              {
                name: '实时大数据演算平台',
                path: '/',
                active: false,
                icon: '',
                level: 'menu-level4',
              },
              {
                name: '分析型分布式数据存储',
                path: '/',
                active: false,
                icon: '',
                level: 'menu-level4',
              },
            ],
          },
          {
            name: '数据应用/数字孪生平台',
            path: '/',
            active: false,
            icon: '',
            level: 'menu-level3',
            children: [
              {
                name: ' 可视化数据分析平台(VBI)',
                path: '/',
                active: false,
                icon: '',
                level: 'menu-level4',
              },
              {
                name: '可视化数屏构建平台',
                path: '/',
                active: false,
                icon: '',
                level: 'menu-level4',
              },
              {
                name: '综合智慧+套件构建平台',
                path: '/',
                active: false,
                icon: '',
                level: 'menu-level4',
              },
              {
                name: '数据挖掘平台',
                path: '/',
                active: false,
                icon: '',
                level: 'menu-level4',
              },
            ],
          },
        ],
      },
      {
        name: '可视化工具',
        path: '/',
        active: false,
        icon: 'view-tool',
        level: 'menu-level2',
        children: [
          {
            name: '通用流程设计工具',
            path: '/',
            active: false,
            icon: '',
          },
          {
            name: '通用表单设计工具',
            path: '/',
            active: false,
            icon: '',
          },
          {
            name: '简易建筑构建器',
            path: '/',
            active: false,
            icon: '',
          },
        ],
      },
    ],
  },
  {
    name: '解决方案',
    path: '/',
    active: false,
    icon: '',
    level: 'menu-level1',
    children: [
      {
        name: '通用方案',
        path: '/',
        active: false,
        icon: '',
        level: 'menu-level2',
      },
      {
        name: '智慧公安',
        path: '/',
        active: false,
        icon: '',
        level: 'menu-level2',
      },
      {
        name: '智慧医疗',
        path: '/',
        active: false,
        icon: '',
        level: 'menu-level2',
      },
      {
        name: '智慧IDC运维',
        path: '/',
        active: false,
        icon: '',
        level: 'menu-level2',
      },
      {
        name: '智慧城市',
        path: '/',
        active: false,
        icon: '',
        level: 'menu-level2',
      },
    ],
  },
  {
    name: '成功案例',
    path: '/',
    active: false,
    icon: '',
    level: 'menu-level1',
  },
  {
    name: '关于我们',
    path: '/',
    active: false,
    icon: '',
    level: 'menu-level1',
  },
  {
    name: '加入我们',
    path: '/',
    active: false,
    icon: '',
    level: 'menu-level1',
  },
]
